const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.SpeechSynthesis,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.SpeechSynthesis.Acts.StopSpeaking,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Touch.Cnds.OnTouchStart
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{bg: 0},
	{Bullet: 0},
	{skyBackground: 0},
	{w: 0},
	{h: 0},
	{Pin: 0},
	{Sine: 0},
	{Sine2: 0},
	{cow: 0},
	{light: 0},
	{btn_sound: 0},
	{full_screen: 0},
	{number: 0},
	{btn_number: 0},
	{action: 0},
	{txt_hud: 0},
	{background_input: 0},
	{btn_confirm: 0},
	{btn_erase: 0},
	{TiledBackground: 0},
	{Mouse: 0},
	{Touch: 0},
	{Browser: 0},
	{ufo: 0},
	{light_ufo: 0},
	{background_question: 0},
	{firefly: 0},
	{Audio: 0},
	{grow: 0},
	{sky: 0},
	{background_timebar: 0},
	{background_timeline: 0},
	{Keyboard: 0},
	{timebar: 0},
	{side: 0},
	{laser_gun: 0},
	{Rotate: 0},
	{laser_rotate: 0},
	{lives: 0},
	{shadow: 0},
	{Fade: 0},
	{correct: 0},
	{incorrect: 0},
	{go: 0},
	{background_info: 0},
	{Rectangle: 0},
	{gameover_bg: 0},
	{game_over: 0},
	{SpeechSynthesis: 0},
	{txt_gameover: 0},
	{bg_info_game_over: 0},
	{btn_retry: 0},
	{btn_menu: 0},
	{txt_button: 0},
	{Text: 0},
	{btn_speech: 0},
	{LocalStorage: 0},
	{logo_aliens: 0},
	{logo_vs: 0},
	{logo_math: 0},
	{mode: 0},
	{btn_option_menu: 0},
	{Group2: 0},
	{Group3: 0},
	{Group4: 0},
	{Group5: 0},
	{Group6: 0},
	{ArrayHighscore: 0},
	{TiledBackground2: 0},
	{btn_default: 0},
	{highscore: 0},
	{txt_menu: 0},
	{polargames: 0},
	{txt_demo: 0},
	{input_buttons: 0},
	{buttons: 0},
	{hud_buttons: 0},
	{logo: 0},
	{user_answer: 0},
	{first_number: 0},
	{second_number: 0},
	{difficulty: 0},
	{operator: 0},
	{result: 0},
	{canPlay: 0},
	{maxTimer: 0},
	{timerCount: 0},
	{score: 0},
	{correct_answers: 0},
	{game_mode: 0},
	{play_time: 0},
	{speeach: 0},
	{sortNumber: 0},
	{forceFastAnimation: 0},
	{hs_correct_answers: 0},
	{hs_play_time: 0},
	{hs_game_mode: 0},
	{LSSound: 0},
	{LsHighscore: 0},
	{lastHighscore: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	skyBackground: class extends self.ITiledBackgroundInstance {},
	cow: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	full_screen: class extends self.ISpriteInstance {},
	btn_number: class extends self.ISpriteInstance {},
	txt_hud: class extends self.ITextInstance {},
	background_input: class extends self.ISpriteInstance {},
	btn_confirm: class extends self.ISpriteInstance {},
	btn_erase: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ufo: class extends self.ISpriteInstance {},
	light_ufo: class extends self.ISpriteInstance {},
	background_question: class extends self.ISpriteInstance {},
	firefly: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	grow: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	background_timebar: class extends self.ITiledBackgroundInstance {},
	background_timeline: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	timebar: class extends self.ISpriteInstance {},
	laser_gun: class extends self.ISpriteInstance {},
	laser_rotate: class extends self.ISpriteInstance {},
	lives: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	correct: class extends self.ISpriteInstance {},
	incorrect: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	background_info: class extends self.ISpriteInstance {},
	Rectangle: class extends self.ISpriteInstance {},
	gameover_bg: class extends self.ISpriteInstance {},
	game_over: class extends self.ISpriteInstance {},
	SpeechSynthesis: class extends self.IInstance {},
	txt_gameover: class extends self.ITextInstance {},
	bg_info_game_over: class extends self.ISpriteInstance {},
	btn_retry: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	txt_button: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	btn_speech: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	logo_aliens: class extends self.ISpriteInstance {},
	logo_vs: class extends self.ISpriteInstance {},
	logo_math: class extends self.ISpriteInstance {},
	btn_option_menu: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Group3: class extends self.ISpriteInstance {},
	Group4: class extends self.ISpriteInstance {},
	Group5: class extends self.ISpriteInstance {},
	Group6: class extends self.ISpriteInstance {},
	ArrayHighscore: class extends self.IArrayInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	btn_default: class extends self.ISpriteInstance {},
	highscore: class extends self.ISpriteInstance {},
	txt_menu: class extends self.ITextInstance {},
	polargames: class extends self.ISpriteInstance {},
	txt_demo: class extends self.ITextInstance {},
	input_buttons: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	hud_buttons: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {}
}